### ISSUE TITLE
Custom method transform specification needs to be clearer

### ISSUE THREAD

**Issue by twalmsley** [MODLanguage/modl.uk#8]
The MODL specification isn't very clear on how to specify the `*transform` field. The examples given in the spec and the test cases in `base_tests.json` use the lowercase long form of the method name, e.g. `replace(two,).trim(.)`, but the `replace` and `trim` method names are shown capitalised in the methods table, is the method name case sensitive? I would expect the names in the core methods table to be lowercase. 

It is also not clear whether the short method names need to be supported by `*transform` as well, e.g. is `r(two,).t(.)` also valid? I would expect the answer to be yes. 

@elliottinvent can you update the spec to clarify please?

**Comment by elliottinvent** [comment]
Will do thanks Tony, the long form should all be lower case as you’ve suggested

**Comment by elliottinvent** [comment]
And methods should be case sensitive

**Comment by twalmsley** [comment]
Ok thanks Elliott, and the short form is valid too?

**Comment by elliottinvent** [comment]
Yes, short form is valid and crucial for character efficiency. Case sensitivity also crucial for character efficiency since it gives us double the amount of one letter method options.

**Comment by twalmsley** [comment]
Good point!

**Comment by twalmsley** [comment]
Closed by mistake.

**Comment by elliottinvent** [comment]
I've changed the method names to lowercase in the methods table. 

There's a "character efficient" version of the custom "hyphenate" method that shows you can use `*t` instead of `*transform` and I've also highlighted below the example that you can use method IDs or names in `*transform` with some additional text. 

@twalmsley if you think this part needs to be made clearer I'm open to suggestions, if you think it's clear now please close this issue.

**Comment by twalmsley** [comment]
Thanks, I think that's fine.
